server:
  port: 8006
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  data:
    redis:
      repositories:
        enabled: false

  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000

mybatis-plus:
  check-config-location: true
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.gitee.app.enums
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      mapper-locations: classpath:mapper/*.xml

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 7200
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格 random-32 random-64 uuid simple-uuid
  token-style: random-32
  # 是否输出操作日志
  is-log: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns:

wx:
  mp:
    useRedis: false
    redisConfig:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
    configs:
      - appId: wxeb99498a302ac0f5 # 第一个公众号的appid
        secret: b278ffaa7a2c76121f900625ff6bb50a # 公众号的appsecret
        token: # 接口配置里的Token值
        aesKey:  # 接口配置里的EncodingAESKey值
      - appId: # 第二个公众号的appid，以下同上
        secret:
        token:
        aesKey:
  ma:
    useRedis: false
    redisConfig:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
    configs:
      - appId: wx432d37972042d2f7 # 第一个小程序的appid
        secret: 36af3dac52242057626d378337a96ffa
        token:
        aesKey:
